#!/bin/bash
## @license AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
## @author Copyright (C) 2015 Robin Schneider <ypid@riseup.net>

# Convert repeative used programs or commands to Sphinx inline syntax.
# http://sphinx-doc.org/markup/inline.html

git ls-files | xargs sed --in-place 's/``\(\/[^`]\+\)``/:file:`\1`/g;s/`rsnapshot``/:program:`rsnapshot`/g;s/``rsync``/:command:`rsync`/g;s/``ssh``/:command:`ssh`/g'
